import { boolean, date, foreignKey, index, integer, jsonb, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const players = pgTable("players", { id: uuid("id").primaryKey(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), latestGameDay: date("latest_game_day") });
export const accounts = pgTable("accounts", { id: uuid("id").primaryKey(), email:text("email").notNull().unique(), playerId:uuid("player_id").notNull().references(()=>players.id).unique() });
export const accountRoles = pgTable("account_roles", { accountId:uuid("account_id").notNull().references(()=>accounts.id,{onDelete:"cascade"}),role:text("role").notNull() },t=>[primaryKey({columns:[t.accountId,t.role]})]);
export const accountSessions = pgTable("account_sessions", { id:uuid("id").primaryKey(), accountId:uuid("account_id").notNull().references(()=>accounts.id,{onDelete:"cascade"}), tokenHash:text("token_hash").notNull().unique(), expiresAt:timestamp("expires_at",{withTimezone:true}).notNull() });
export const guestCredentials = pgTable("guest_credentials", { playerId:uuid("player_id").primaryKey().references(()=>players.id,{onDelete:"cascade"}),tokenHash:text("token_hash").notNull().unique(),revokedAt:timestamp("revoked_at",{withTimezone:true}),mergedAccountId:uuid("merged_account_id").references(()=>accounts.id),priorAccountTokenHash:text("prior_account_token_hash"),mergeReceiptExpiresAt:timestamp("merge_receipt_expires_at",{withTimezone:true}) });
export const magicLinks = pgTable("magic_links", {id:uuid("id").primaryKey(),email:text("email").notNull(),tokenHash:text("token_hash").notNull().unique(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),consumedAt:timestamp("consumed_at",{withTimezone:true})});
export const sessions = pgTable("sessions", { id: uuid("id").primaryKey(), playerId: uuid("player_id").notNull().references(() => players.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull() });
export const boards = pgTable("boards", { id: text("id").primaryKey(), title: text("title").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const boardVersions = pgTable("board_versions", { boardId: text("board_id").notNull().references(() => boards.id), version: integer("version").notNull(), gameDay: date("game_day"), payload: jsonb("payload").notNull(),state:text("state").notNull().default("Draft"), publishedAt: timestamp("published_at", { withTimezone: true }) }, t => [primaryKey({ columns: [t.boardId, t.version] })]);
export const scheduleAssignments = pgTable("schedule_assignments", { gameDay: date("game_day").primaryKey(), boardId: text("board_id").notNull(), boardVersion: integer("board_version").notNull(), published: boolean("published").notNull().default(false) }, t => [foreignKey({ columns: [t.boardId, t.boardVersion], foreignColumns: [boardVersions.boardId, boardVersions.version] })]);
export const plays = pgTable("plays", {
  id: uuid("id").primaryKey(), playerId: uuid("player_id").notNull().references(() => players.id), boardId: text("board_id").notNull(), boardVersion: integer("board_version").notNull(), gameDay: date("game_day").notNull(), boardGameDay: date("board_game_day"), playedAt: timestamp("played_at", { withTimezone: true }).notNull(), mode: text("mode").notNull(), hintMode: text("hint_mode").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), finishedAt: timestamp("finished_at", { withTimezone: true }), score: integer("score"), elapsedMs: integer("elapsed_ms"), hintUsed: boolean("hint_used"), authoritativeResult: jsonb("authoritative_result"), rankingEligible: boolean("ranking_eligible").notNull().default(true)
}, t => [foreignKey({ columns: [t.boardId, t.boardVersion], foreignColumns: [boardVersions.boardId, boardVersions.version] }), uniqueIndex("one_daily_per_player_day").on(t.playerId, t.gameDay, t.mode).where(sql`${t.mode} = 'daily'`), uniqueIndex("one_archive_per_player_board").on(t.playerId, t.boardId, t.boardVersion).where(sql`${t.mode} = 'archive'`), index("ranking_day_pool").on(t.gameDay, t.hintMode, t.rankingEligible)]);
export const streaks = pgTable("streaks", { playerId: uuid("player_id").notNull().references(() => players.id), kind: text("kind").notNull(), current: integer("current").notNull().default(0), best: integer("best").notNull().default(0), lastGameDay: date("last_game_day") }, t => [primaryKey({ columns: [t.playerId, t.kind] })]);
export const achievementUnlocks = pgTable("achievement_unlocks", { playerId: uuid("player_id").notNull().references(() => players.id), achievementId: text("achievement_id").notNull(), unlockedAt: timestamp("unlocked_at", { withTimezone: true }).notNull().defaultNow() }, t => [primaryKey({ columns: [t.playerId, t.achievementId] })]);
export const auditEvents = pgTable("audit_events", { id: uuid("id").primaryKey(), playerId: uuid("player_id").references(() => players.id),actorAccountId:uuid("actor_account_id").references(()=>accounts.id), playId: uuid("play_id").references(() => plays.id), kind: text("kind").notNull(), payload: jsonb("payload").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
