import {afterAll,beforeAll,beforeEach,describe,expect,it} from "vitest";
import postgres,{type Sql} from "postgres";
import {readFile} from "node:fs/promises";
import {createScheduler} from "./scheduler.js";

const url=process.env.TEST_DATABASE_URL??"postgres://kcorless@127.0.0.1:55432/d10net_test";
describe("publisher scheduler",()=>{const schema=`scheduler_${crypto.randomUUID().replaceAll("-","")}`;let admin:Sql,sql:Sql;
  beforeAll(async()=>{admin=postgres(url,{max:1});await admin.unsafe(`create schema "${schema}"`);sql=postgres(url,{max:8,connection:{search_path:schema}});const initial=(await readFile(new URL("./db/migrations/0001_initial.sql",import.meta.url),"utf8")).replaceAll('"public".',`"${schema}".`);for(const statement of initial.split("--> statement-breakpoint").map(x=>x.trim()).filter(Boolean))await sql.unsafe(statement);const migration=await readFile(new URL("./db/migrations/0002_publisher.sql",import.meta.url),"utf8");for(const statement of migration.split(";").map(x=>x.trim()).filter(Boolean))await sql.unsafe(statement)});
  afterAll(async()=>{await sql?.end();await admin?.unsafe(`drop schema if exists "${schema}" cascade`);await admin?.end()});
  beforeEach(async()=>{await sql`delete from audit_events`;await sql`delete from schedule_assignments`;await sql`delete from board_versions`;await sql`delete from boards`});
  async function board(id:string,state="Validated",gameDay:string|null=null){await sql`insert into boards(id,title) values(${id},${id})`;await sql`insert into board_versions(board_id,version,game_day,payload,state) values(${id},1,${gameDay},${sql.json({id})},${state})`}
  it("preserves an explicit assignment",async()=>{await board("explicit","Scheduled","2026-07-12");await sql`insert into schedule_assignments(game_day,board_id,board_version) values('2026-07-12','explicit',1)`;const result=await createScheduler(sql,{}).ensureNextBoard("2026-07-12",()=>0);expect(result).toMatchObject({source:"explicit",boardId:"explicit",boardVersion:1})});
  it("randomly assigns one unused validated board using the injected RNG without theme balance",async()=>{await board("alpha");await board("beta");await board("used","Scheduled","2026-07-01");await sql`insert into schedule_assignments(game_day,board_id,board_version) values('2026-07-01','used',1)`;const result=await createScheduler(sql,{}).ensureNextBoard("2026-07-13",()=>0.5);expect(result).toMatchObject({source:"random",boardId:"beta"})});
  it("is idempotent across retries and concurrent calls",async()=>{await board("only");const scheduler=createScheduler(sql,{}),results=await Promise.all(Array.from({length:8},()=>scheduler.ensureNextBoard("2026-07-13",()=>0)));expect(new Set(results.map(x=>`${x.boardId}:${x.boardVersion}`))).toEqual(new Set(["only:1"]));expect((await sql`select * from schedule_assignments where game_day='2026-07-13'`)).toHaveLength(1);expect((await sql`select * from audit_events where kind='publisher_board_scheduled'`)).toHaveLength(1)});
  it("audits a random assignment",async()=>{await board("audited");await createScheduler(sql,{}).ensureNextBoard("2026-07-13",()=>0);const [event]=await sql`select kind,payload from audit_events`;expect(event).toMatchObject({kind:"publisher_board_scheduled",payload:{gameDay:"2026-07-13",boardId:"audited",boardVersion:1,source:"random"}})});
  it("alerts on an empty pool and uses the configured emergency board",async()=>{await board("emergency");const result=await createScheduler(sql,{emergencyBoard:{id:"emergency",version:1}}).ensureNextBoard("2026-07-14",()=>0);expect(result.source).toBe("emergency");const events=await sql`select kind,payload from audit_events`;expect(events).toHaveLength(2);expect(events).toEqual(expect.arrayContaining([expect.objectContaining({kind:"publisher_pool_empty",payload:{gameDay:"2026-07-14"}}),expect.objectContaining({kind:"publisher_board_scheduled",payload:expect.objectContaining({source:"emergency"})})]))});
  it("does not call or validate the RNG when the normal pool is empty",async()=>{await board("emergency");let called=false;const result=await createScheduler(sql,{emergencyBoard:{id:"emergency",version:1}}).ensureNextBoard("2026-07-14",()=>{called=true;throw new Error("must not run")});expect(result.source).toBe("emergency");expect(called).toBe(false);expect((await sql`select kind from audit_events where kind='publisher_pool_empty'`)).toHaveLength(1)});
  it("fails only when both the normal pool and emergency board are unavailable",async()=>{await expect(createScheduler(sql,{emergencyBoard:{id:"missing",version:1}}).ensureNextBoard("2026-07-14",()=>0)).rejects.toThrow(/emergency board unavailable/i);expect((await sql`select kind from audit_events`).map(x=>x.kind)).toEqual(["publisher_pool_empty"])});
});
